### ISSUE TITLE
Reification points to RDF 1.1 Concepts, which does not talk about reification

### ISSUE THREAD

**Issue by aidhog** [Knowledge-Graphs-Book/HTML-Book#17]
In Section 3.3.2 the book cites the [RDF *1.1* spec for RDF reification](https://www.w3.org/TR/rdf11-concepts/), but the spec does not mention RDF reification. (Thanks to Stefan Bischof for pointing this out.)

Probably need to cite something else here. 

Was reification deprecated in RDF 1.1? The concepts document seems to be silent on reification, collections, and lists, but presumably at least lists are still part of the standard (OWL depends on them). Also the [RDF 1.1 Semantics document](https://www.w3.org/TR/rdf11-mt/) still considers vocabulary like `rdf:subject`, `rdf:List`, etc.

**Comment by Antoine-Zimmermann** [comment]
RDF reification is something that RDF Schema deals with. Like lists, containers etc. RDF semantics provides the semantics not only to the basic abstract syntax of RDF, but also to the RDFS vocabulary. The RDFS vocabulary contains all the terms defined under `rdf:` and `rdfs:` namespaces because the distinction between `rdf:` and `rdfs:` is merely an accident of history.

**Comment by Antoine-Zimmermann** [comment]
So, the reference we must put for RDF reification is [RDF 1.1 Schema, Section 5.3](https://www.w3.org/TR/rdf-schema/#ch_reificationvocab).

**Comment by stefanbischof** [comment]
Thank you for the clarification Antoine!

**Comment by aidhog** [comment]
Changed the reference to the RDFS spec in the HTML, PHP and LaTeX. 

(Likewise changed the reference for n-ary relations to RDFS 1.1 instead of RDF 1.1. It's not ideal as the RDFS 1.1 spec does not mention the phrase n-ary relation, but it does define `rdf:value` at least. We don't have a better ref in the bib.)
